// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxZCqXYidxOytT2iYIQXeKtZ7qdsav84',
    appId: '1:634884676204:web:9140aeea15f117b17a5649',
    messagingSenderId: '634884676204',
    projectId: 'attendance-app-88fcf',
    authDomain: 'attendance-app-88fcf.firebaseapp.com',
    storageBucket: 'attendance-app-88fcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCei4a_ozPJWeKmmwaUz2T60XYi_Kx21QQ',
    appId: '1:634884676204:android:5bde8f6dbd8d9ac57a5649',
    messagingSenderId: '634884676204',
    projectId: 'attendance-app-88fcf',
    storageBucket: 'attendance-app-88fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzSf95qjRh3OK6duqDn3R8Wr1y8_JPno',
    appId: '1:634884676204:ios:41125ffe231c24af7a5649',
    messagingSenderId: '634884676204',
    projectId: 'attendance-app-88fcf',
    storageBucket: 'attendance-app-88fcf.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzSf95qjRh3OK6duqDn3R8Wr1y8_JPno',
    appId: '1:634884676204:ios:41125ffe231c24af7a5649',
    messagingSenderId: '634884676204',
    projectId: 'attendance-app-88fcf',
    storageBucket: 'attendance-app-88fcf.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHxZCqXYidxOytT2iYIQXeKtZ7qdsav84',
    appId: '1:634884676204:web:ef5968fe09b5f8e27a5649',
    messagingSenderId: '634884676204',
    projectId: 'attendance-app-88fcf',
    authDomain: 'attendance-app-88fcf.firebaseapp.com',
    storageBucket: 'attendance-app-88fcf.firebasestorage.app',
  );
}
